config/routes.rb
Rails.application.routes.draw do
  root "habits#index"
  post "/habits/toggle_complete/:id", to: "habits#toggle_complete", as: "toggle_complete"

  resources :habits
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/habit.rb
class Habit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  def index
    @habits = Habit.all.order(:complete)
  end

  def new
    @habit = Habit.new
  end

  def create
    @habit = Habit.new(habit_params)
    @habit.complete = false

    if @habit.save
      
      redirect_to :root
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @habit = Habit.find(params[:id])
    @habit.destroy

    redirect_to :root
  end

  def toggle_complete
    @habit = Habit.find(params[:id])
    @habit.toggle! :complete

    redirect_to :root
  end

  private
    def habit_params
      params.require(:habit).permit(:name, :timespan)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/views/habits/_new_habit.html.erb
<%= form_for :habit, url: habits_path do |f| %>
  <%= f.text_field :name %>

  <div class="field">
    <%= f.radio_button :timespan, :daily %>
    <%= f.label :timespan, "Daily" %>
    <%= f.radio_button :timespan, :weekly %>
    <%= f.label :timespan, "Weekly" %>
    <%= f.radio_button :timespan, :monthly %>
    <%= f.label :timespan, "Monthly" %>
  </div>
  
  <%= f.submit "Add" %>
<% end %>

app/views/habits/index.html.erb
<h1>Habits</h1>

<ul>
  <% @habits.each do |habit| %>
    <li>
      <%# TODO: Prototype, using a checkbox and style name better. %>
      <% if habit.complete %>
        <% checkbox = "[x]" %>
        <% style = "text-decoration:line-through;" %>
      <% else %>
        <% checkbox = "[ ]" %>
        <% style = "" %>
      <% end %>

      <%= button_to checkbox, toggle_complete_path(habit), method: :post, form: {style: "display:inline;"} %>

      <span style=<%= style %>>
        <%= habit.name %>
      </span>

      <%= button_to "x", habit, :method => "delete", form: {style: "display:inline;"} %>

      <span style="color:gray;">(<%= habit.timespan %>)</span>
    </li>
  <% end %>
</ul>

<%= render "new_habit" %>

app/views/habits/toggle_done.html.erb
<%# Empty page %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Habits</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>